# Generated by Django 3.0.3 on 2020-02-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Waiting to pick up for delivery'), (3, 'In delivery'), (4, 'Delivered'), (5, 'Cancelled')], default=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
