# Generated by Django 3.0.3 on 2020-02-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminorder',
            old_name='ordered',
            new_name='is_ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_active',
            new_name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='iteminorder',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='core.ItemInOrder'),
        ),
        migrations.AlterField(
            model_name='iteminorder',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product'),
        ),
    ]
